-- restaurantsテーブル
INSERT IGNORE INTO restaurants (id, name, image_name, description, lowest_price, highest_price, capacity, postal_code, address, phone_number, open_time, close_time, regular_holiday, category) VALUES (1, '＆ BLES', 'restaurant07.jpg', '栄駅徒歩5分。様々なデザインの豪華個室多数完備。自慢の料理をごゆっくりご堪能ください。', 3000, 3999, 40, '460-0003', '愛知県名古屋市中区錦X-XX-XX', '012-345-678', '18:00', '05:00', '不定休', '居酒屋、バー、イタリア料理');
INSERT IGNORE INTO restaurants (id, name, image_name, description, lowest_price, highest_price, capacity, postal_code, address, phone_number, open_time, close_time, regular_holiday, category) VALUES (2, '韓国ダイニング ノミスニダ', 'restaurant02.jpg', '金山駅から3分。楽しいが沢山詰まったKPOP好きイチオシ空間で韓国料理を楽しむ。', 4000, 4999, 100, '460-0022', '愛知県名古屋市中区金山X-XX-XX', '012-345-678', '18:00', '02:00', '水', '居酒屋、韓国料理、焼肉');
INSERT IGNORE INTO restaurants (id, name, image_name, description, lowest_price, highest_price, capacity, postal_code, address, phone_number, open_time, close_time, regular_holiday, category) VALUES (3, 'こだわり料理 菜々美', 'restaurant03.jpg', '64種類の『お茶割』と共に元鰻屋の料理長が作る和風創作料理を楽しむ♪落ち着きのある和空間◎', 4000, 4999, 45, '460-0003', '愛知県名古屋市中区錦X-XX-XX', '012-345-678', '17:00', '02:00', '日', '居酒屋、和食、海鮮料理');
INSERT IGNORE INTO restaurants (id, name, image_name, description, lowest_price, highest_price, capacity, postal_code, address, phone_number, open_time, close_time, regular_holiday, category) VALUES (4, 'らぁ麺　青紫花', 'restaurant04.jpg', '鶏の旨味や甘みを究極まで引き出したスープ', 1000, 1999, 14, '460-0003', '愛知県名古屋市中川区X-XX-XX', '012-345-678', '10:00', '15:00', '月', 'ラーメン');
INSERT IGNORE INTO restaurants (id, name, image_name, description, lowest_price, highest_price, capacity, postal_code, address, phone_number, open_time, close_time, regular_holiday, category) VALUES (5, '麺家 獅子九', 'restaurant05.jpg', '【名古屋駅5分】洋を取り入れたラーメン店。時季折々の食材を駆使した店主の気まぐれを楽しむ', 1000, 1999, 13, '460-0003', '愛知県名古屋市中村区亀島X-XX-XX', '012-345-678', '11:00', '19:00', '年中無休', 'ラーメン');
INSERT IGNORE INTO restaurants (id, name, image_name, description, lowest_price, highest_price, capacity, postal_code, address, phone_number, open_time, close_time, regular_holiday, category) VALUES (6, 'えびそば 彩', 'restaurant06.jpg', '人気絶頂！海老に特化した最高の「えびそば」。海老と麺に拘ったオンリーワンの「えびそば」専門店。', 800, 1999, 17, '460-0003', '愛知県名古屋市瑞穂区前町X-XX-XX', '012-345-678', '11:00', '21:00', '月', 'ラーメン、そば、うどん');
INSERT IGNORE INTO restaurants (id, name, image_name, description, lowest_price, highest_price, capacity, postal_code, address, phone_number, open_time, close_time, regular_holiday, category) VALUES (7, 'トリュフ・ファンキー', 'restaurant01.jpg', 'トリュフを使ったフランス料理をご堪能ください。', 3000, 12000, 17, '460-0003', '愛知県名古屋市中区錦X-XX-XX', '012-345-678', '11:00', '20:00', '水', 'フランス料理');
INSERT IGNORE INTO restaurants (id, name, image_name, description, lowest_price, highest_price, capacity, postal_code, address, phone_number, open_time, close_time, regular_holiday, category) VALUES (8, 'キャッパ寿司', 'restaurant14.jpg', '新鮮な魚とトリッキーなネタが毎回飛び出す。小さなお子様から大きなお子様まで楽しめます。', 1500, 8000, 120, '460-0003', '愛知県名古屋市中区錦X-XX-XX', '012-345-678', '10:00', '21:00', '年中無休', '寿司、天ぷら、和食');
INSERT IGNORE INTO restaurants (id, name, image_name, description, lowest_price, highest_price, capacity, postal_code, address, phone_number, open_time, close_time, regular_holiday, category) VALUES (9, 'ハンバーグ師匠', 'restaurant08.jpg', '一口食べたら「ハンバーグ！」と叫びたくなるような、肉厚でジューシーなハンバーグ。ファミリーでも楽しめます。', 2000, 4999, 30, '460-0003', '愛知県名古屋市中区錦X-XX-XX', '012-345-678', '10:00', '02:00', '年中無休', 'ハンバーグ、ステーキ、ラーメン、焼肉、スイーツ、洋食');
INSERT IGNORE INTO restaurants (id, name, image_name, description, lowest_price, highest_price, capacity, postal_code, address, phone_number, open_time, close_time, regular_holiday, category) VALUES (10, 'ケーキ屋 ジャンボ', 'restaurant10.jpg', '豊富な種類と程よい甘さが売りのスイーツ専門店。いくら食べてもカロリーゼロです。', 1000, 3000, 10, '460-0003', '愛知県名古屋市中区錦X-XX-XX', '012-345-678', '10:00', '18:00', '土、日', 'スイーツ、ケーキ、喫茶店');
INSERT IGNORE INTO restaurants (id, name, image_name, description, lowest_price, highest_price, capacity, postal_code, address, phone_number, open_time, close_time, regular_holiday, category) VALUES (11, '焼き鳥専門店 トリッピー', 'restaurant12.jpg', '名古屋コーチンを炭火で絶妙に焼きあげております。焼き鳥専門とうたっておりますが、いろいろありますのでぜひお越しください。', 800, 4999, 20, '460-0003', '愛知県名古屋市中区錦X-XX-XX', '012-345-678', '8:00', '23:00', '年中無休', '焼き鳥、焼肉、ラーメン、うどん、牛丼、親子丼、和食、洋食');
INSERT IGNORE INTO restaurants (id, name, image_name, description, lowest_price, highest_price, capacity, postal_code, address, phone_number, open_time, close_time, regular_holiday, category) VALUES (12, '鳳玲仙', 'restaurant11.jpg', '中国4000年の歴史をふんだんに利用した中華料理をご堪能ください。和食もあります。', 1000, 3000, 100, '460-0003', '愛知県名古屋市中区錦X-XX-XX', '012-345-678', '10:00', '21:00', '年中無休', '中華料理、和食、居酒屋');
INSERT IGNORE INTO restaurants (id, name, image_name, description, lowest_price, highest_price, capacity, postal_code, address, phone_number, open_time, close_time, regular_holiday, category) VALUES (13, 'ラドュ・パスカル・ド・セミラベーゼ', 'restaurant09.jpg', '豊富な種類のパスタが食べ放題！竈で焼いたピッツァもおすすめです。', 2500, 5000, 40, '460-0003', '愛知県名古屋市中区錦X-XX-XX', '012-345-678', '10:00', '17:00', '水', 'パスタ、イタリア料理、パン');
INSERT IGNORE INTO restaurants (id, name, image_name, description, lowest_price, highest_price, capacity, postal_code, address, phone_number, open_time, close_time, regular_holiday, category) VALUES (14, 'ヨガファイヤー', 'restaurant13.jpg', '28種類のスパイスを丁寧にブレンドしたカレーが自慢。つくりたてなのにまるで3日間寝かせたような味をぜひご堪能ください。', 1000, 2000, 12, '460-0003', '愛知県名古屋市中区錦X-XX-XX', '012-345-678', '13:00', '18:00', '金', 'カレー、インド料理');
INSERT IGNORE INTO restaurants (id, name, image_name, description, lowest_price, highest_price, capacity, postal_code, address, phone_number, open_time, close_time, regular_holiday, category) VALUES (15, 'シェフの気まぐれ', 'restaurant11.jpg', 'まさにシェフの気まぐれで作った創作料理をご堪能ください。', 1000, 10000, 5, '460-0003', '愛知県名古屋市中区錦X-XX-XX', '012-345-678', '14:00', '17:00', '月、水、金', 'イタリア料理、フランス料理、和食、洋食、スイーツ');
INSERT IGNORE INTO restaurants (id, name, image_name, description, lowest_price, highest_price, capacity, postal_code, address, phone_number, open_time, close_time, regular_holiday, category) VALUES (16, 'ビックり・ボーイ', 'b4bdca5e-f911-4279-b111-0eaf229b407c.jpg', 'ステーキあります。', 2000, 3000, 50, '460-0022',	'東京都名古屋市中区＊＊－＊＊－＊＊', '090-1234-5678', '11:00', '01:00', '年中無休', '洋食、ステーキ、ハンバーグ');
INSERT IGNORE INTO restaurants (id, name, image_name, description, lowest_price, highest_price, capacity, postal_code, address, phone_number, open_time, close_time, regular_holiday, category) VALUES (17, 'カフェ六兵衛', '09dddca6-f0fe-4700-9bcc-a13bc0aa5f34.jpg', '創業60周年。本場フランス菓子とワンランク上のカフェ＆ティータイムをお楽しみください。', 1000, 2000, 20, '460-0023', '愛知県名古屋市北区上飯田××ー××', '050-5555-5678', '09:30', '18:30', '年中無休', 'カフェ、ケーキ、パスタ');
INSERT IGNORE INTO restaurants (id, name, image_name, description, lowest_price, highest_price, capacity, postal_code, address, phone_number, open_time, close_time, regular_holiday, category) VALUES (18, 'What’s French food?', '0d81fe33-d8c7-41cb-8f0c-4a2968c5ce33.jpg', 'フレンチベースの多彩な逸品をワインとともに味わえるビストロ。ランチも◎', 2999, 4999, 22, '460-4682', '愛知県名古屋市中区栄×―×', '050-9874-6543', '11:30', '21;00', '日', '洋食、フランス料理、パスタ');
INSERT IGNORE INTO restaurants (id, name, image_name, description, lowest_price, highest_price, capacity, postal_code, address, phone_number, open_time, close_time, regular_holiday, category) VALUES (19, 'キッチョンなごや', 'db8157b1-2016-4523-a5b0-42da049c603f.jpg', '名古屋名物を集めた「名古屋ぜいたく定食」は一番人気！ 「名古屋名物セット」も食べてちょうよ！', 2000, 3000, 47, '460-0003', '愛知県名古屋市中村区××―××', '052-544-3320', '10:30', '22:00', '水', '居酒屋、とんかつ、洋食、和食');
INSERT IGNORE INTO restaurants (id, name, image_name, description, lowest_price, highest_price, capacity, postal_code, address, phone_number, open_time, close_time, regular_holiday, category) VALUES (20, '鉄板焼き　ジュージュー',	'c06f3e13-a39f-4eff-bf42-3dc606a3eb37.jpg', 'お好み焼きなどの鉄板料理をはじめ、新感覚の焼き鳥“今治焼き”や希少な伊賀牛を使用した贅沢な逸品♪ご宴会に最適なコースも2,500円～ご用意しておりまジュー。', 2000, 5000, 50, '460-0023', '愛知県名古屋市東区泉××―××', '050-8888-9999', '17:00', '23:00', '年中無休', 'お好み焼き、居酒屋、たこ焼き');
INSERT IGNORE INTO restaurants (id, name, image_name, description, lowest_price, highest_price, capacity, postal_code, address, phone_number, open_time, close_time, regular_holiday, category) VALUES (21, 'すきだが家', '9cd4ff7f-26a0-4e58-a2cc-04206ea07cff.jpg', 'あの全国牛丼チェーン店と変わらぬ味をお届けいたします。', 500, 1500, 15,	'460-0022', '愛知県名古屋市中区＊＊－＊＊－＊＊', '056-8800-9900', '10:00', '02:00', '年中無休', '牛丼、和食、居酒屋');

-- rolesテーブル
INSERT IGNORE INTO roles (id, name) VALUES (1, 'ROLE_GENERAL');
INSERT IGNORE INTO roles (id, name) VALUES (2, 'ROLE_ADMIN');

-- usersテーブル
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (1, '侍 太郎', 'サムライ タロウ', '101-0022', '東京都千代田区神田練塀町300番地', '090-1234-5678', 'taro.samurai@example.com', '$2a$10$2JNjTwZBwo7fprL2X4sv.OEKqxnVtsVQvuXDkI8xVGix.U3W5B7CO', 1, true);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (2, '侍 花子', 'サムライ ハナコ', '101-0022', '東京都千代田区神田練塀町300番地', '090-1234-5678', 'hanako.samurai@example.com', '$2a$10$2JNjTwZBwo7fprL2X4sv.OEKqxnVtsVQvuXDkI8xVGix.U3W5B7CO', 2, true);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (3, '侍 義勝', 'サムライ ヨシカツ', '638-0644', '奈良県五條市西吉野町湯川X-XX-XX', '090-1234-5678', 'yoshikatsu.samurai@example.com', 'password', 1, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (4, '侍 幸美', 'サムライ サチミ', '342-0006', '埼玉県吉川市南広島X-XX-XX', '090-1234-5678', 'sachimi.samurai@example.com', 'password', 1, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (5, '侍 雅', 'サムライ ミヤビ', '527-0209', '滋賀県東近江市佐目町X-XX-XX', '090-1234-5678', 'miyabi.samurai@example.com', 'password', 1, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (6, '侍 正保', 'サムライ マサヤス', '989-1203', '宮城県柴田郡大河原町旭町X-XX-XX', '090-1234-5678', 'masayasu.samurai@example.com', 'password', 1, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (7, '侍 真由美', 'サムライ マユミ', '951-8015', '新潟県新潟市松岡町X-XX-XX', '090-1234-5678', 'mayumi.samurai@example.com', 'password', 1, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (8, '侍 安民', 'サムライ ヤスタミ', '241-0033', '神奈川県横浜市旭区今川町X-XX-XX', '090-1234-5678', 'yasutami.samurai@example.com', 'password', 1, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (9, '侍 章緒', 'サムライ アキオ', '739-2103', '広島県東広島市高屋町宮領X-XX-XX', '090-1234-5678', 'akio.samurai@example.com', 'password', 1, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (10, '侍 祐子', 'サムライ ユウコ', '601-0761', '京都府南丹市美山町高野X-XX-XX', '090-1234-5678', 'yuko.samurai@example.com', 'password', 1, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (11, '侍 秋美', 'サムライ アキミ', '606-8235', '京都府京都市左京区田中西春菜町X-XX-XX', '090-1234-5678', 'akimi.samurai@example.com', 'password', 1, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (12, '侍 信平', 'サムライ シンペイ', '673-1324', '兵庫県加東市新定X-XX-XX', '090-1234-5678', 'shinpei.samurai@example.com', 'password', 1, false);

-- reservationsテーブル
INSERT IGNORE INTO reservations (id, restaurant_id, user_id, checkin_date, reservation_time, number_of_people) VALUES (1, 1, 1, '2023-04-01', '12:30', 2);
INSERT IGNORE INTO reservations (id, restaurant_id, user_id, checkin_date, reservation_time, number_of_people) VALUES (2, 2, 1, '2023-04-01', '13:00', 3);
INSERT IGNORE INTO reservations (id, restaurant_id, user_id, checkin_date, reservation_time, number_of_people) VALUES (3, 3, 1, '2023-04-01', '13:30', 4);
INSERT IGNORE INTO reservations (id, restaurant_id, user_id, checkin_date, reservation_time, number_of_people) VALUES (4, 4, 1, '2023-04-01', '14:00', 5);
INSERT IGNORE INTO reservations (id, restaurant_id, user_id, checkin_date, reservation_time, number_of_people) VALUES (5, 5, 1, '2023-04-01', '14:30', 6);
INSERT IGNORE INTO reservations (id, restaurant_id, user_id, checkin_date, reservation_time, number_of_people) VALUES (6, 6, 1, '2023-04-01', '11:30', 2);
INSERT IGNORE INTO reservations (id, restaurant_id, user_id, checkin_date, reservation_time, number_of_people) VALUES (7, 7, 1, '2023-04-01', '12:30', 3);
INSERT IGNORE INTO reservations (id, restaurant_id, user_id, checkin_date, reservation_time, number_of_people) VALUES (8, 8, 1, '2023-04-01', '16:00', 4);
INSERT IGNORE INTO reservations (id, restaurant_id, user_id, checkin_date, reservation_time, number_of_people) VALUES (9, 9, 1, '2023-04-01', '15:00', 5);
INSERT IGNORE INTO reservations (id, restaurant_id, user_id, checkin_date, reservation_time, number_of_people) VALUES (10, 10, 1, '2023-04-01', '12:00', 6);
INSERT IGNORE INTO reservations (id, restaurant_id, user_id, checkin_date, reservation_time, number_of_people) VALUES (11, 11, 1, '2023-04-01', '12:30', 2);

-- reviewsテーブル
INSERT IGNORE INTO reviews (id, user_id, restaurant_id, score, content, created_at, updated_at) VALUES (1, 2, 1, 3, 'まあまあ良かった', NOW(), NOW());
INSERT IGNORE INTO reviews (id, user_id, restaurant_id, score, content, created_at, updated_at) VALUES (2, 3, 1, 4, '結構良かった', NOW(), NOW());
INSERT IGNORE INTO reviews (id, user_id, restaurant_id, score, content, created_at, updated_at) VALUES (3, 4, 1, 5, '最高！', NOW(), NOW());
INSERT IGNORE INTO reviews (id, user_id, restaurant_id, score, content, created_at, updated_at) VALUES (4, 5, 1, 4, 'また来たい', NOW(), NOW());
INSERT IGNORE INTO reviews (id, user_id, restaurant_id, score, content, created_at, updated_at) VALUES (5, 6, 1, 2, '料理が普通', NOW(), NOW());
INSERT IGNORE INTO reviews (id, user_id, restaurant_id, score, content, created_at, updated_at) VALUES (6, 7, 1, 1, '応対が悪かった', NOW(), NOW());
INSERT IGNORE INTO reviews (id, user_id, restaurant_id, score, content, created_at, updated_at) VALUES (7, 8, 1, 3, '部屋が広い', NOW(), NOW());
INSERT IGNORE INTO reviews (id, user_id, restaurant_id, score, content, created_at, updated_at) VALUES (8, 9, 1, 3, 'アクセスが良い', NOW(), NOW());
INSERT IGNORE INTO reviews (id, user_id, restaurant_id, score, content, created_at, updated_at) VALUES (9, 10, 1, 4, '料理が上手い', NOW(), NOW());
INSERT IGNORE INTO reviews (id, user_id, restaurant_id, score, content, created_at, updated_at) VALUES (10, 11, 1, 5, '値段が安い', NOW(), NOW());

-- favoritesテーブル
INSERT IGNORE INTO favorites (id, user_id, restaurant_id, created_at, updated_at) VALUES (1, 1, 1, NOW(), NOW());
INSERT IGNORE INTO favorites (id, user_id, restaurant_id, created_at, updated_at) VALUES (2, 1, 5, NOW(), NOW());
INSERT IGNORE INTO favorites (id, user_id, restaurant_id, created_at, updated_at) VALUES (3, 1, 8, NOW(), NOW());
INSERT IGNORE INTO favorites (id, user_id, restaurant_id, created_at, updated_at) VALUES (4, 1, 9, NOW(), NOW());
INSERT IGNORE INTO favorites (id, user_id, restaurant_id, created_at, updated_at) VALUES (5, 1, 12, NOW(), NOW());
INSERT IGNORE INTO favorites (id, user_id, restaurant_id, created_at, updated_at) VALUES (6, 1, 13, NOW(), NOW());
INSERT IGNORE INTO favorites (id, user_id, restaurant_id, created_at, updated_at) VALUES (7, 1, 14, NOW(), NOW());
